copy bios\ibmbio.com %1
copy dos\IBMDOS.COM %1
copy cmd\chkdsk\CHKDSK.COM %1
copy cmd\command\COMMAND.COM %1
copy cmd\debug\DEBUG.COM %1
copy cmd\diskcopy\DISKCOPY.COM %1
copy cmd\edlin\EDLIN.COM %1
copy cmd\exe2bin\EXE2BIN.EXE %1
copy cmd\fc\FC.EXE %1
copy cmd\find\FIND.EXE %1
copy cmd\format\FORMAT.COM %1
copy cmd\more\MORE.COM %1
copy cmd\print\PRINT.COM %1
copy cmd\recover\RECOVER.COM %1
copy cmd\sort\SORT.EXE %1
copy cmd\sys\SYS.COM %1
